#pragma once

#include <stdint.h>

#define DJSW_MAX_ANALOG_INTERPOLATION_COUNT 32

#define DJSW_IDX_ANALOG_INTERPOLATION_CROSSFADER 0

#define DJSW_IDX_ANALOG_INTERPOLATION_VOLUME1 1
#define DJSW_IDX_ANALOG_INTERPOLATION_VOLUME2 2
#define DJSW_IDX_ANALOG_INTERPOLATION_VOLUME3 3
#define DJSW_IDX_ANALOG_INTERPOLATION_VOLUME4 4

#define DJSW_IDX_ANALOG_INTERPOLATION_TEMPO1 5
#define DJSW_IDX_ANALOG_INTERPOLATION_TEMPO2 6
#define DJSW_IDX_ANALOG_INTERPOLATION_TEMPO3 7
#define DJSW_IDX_ANALOG_INTERPOLATION_TEMPO4 8

#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_LO1 9
#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_MD1 10
#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_HI1 11
#define DJSW_IDX_ANALOG_INTERPOLATION_FX1 12

#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_LO2 13
#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_MD2 14
#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_HI2 15
#define DJSW_IDX_ANALOG_INTERPOLATION_FX2 16

#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_LO3 17
#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_MD3 18
#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_HI3 19
#define DJSW_IDX_ANALOG_INTERPOLATION_FX3 20

#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_LO4 21
#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_MD4 22
#define DJSW_IDX_ANALOG_INTERPOLATION_EQ_HI4 23
#define DJSW_IDX_ANALOG_INTERPOLATION_FX4 24

#define DJSW_ANALOG_VALUE_MIN 0
#define DJSW_ANALOG_VALUE_MID 127
#define DJSW_ANALOG_VALUE_MAX 255

void SetAnalogValue(uint8_t value, int index);
uint8_t GetAnalogValueInt(int index);
float GetAnalogValueFloat(int index);

int32_t GetPosition(int channel);
void PeekSample(int16_t* out, int channel, int32_t position);
bool IsAudioLoaded(int channel);

// TEST
AudioChannel* GetChannel(int index);